# Generated by Django 6.0.3 on 2026-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_comment_user_alter_like_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="comment",
            name="username",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
