# Generated by Django 6.0.3 on 2026-04-17 00:03

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comment_avatar_comment_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/",
                validators=[posts.models.validate_image_file],
            ),
        ),
    ]
