# Generated by Django 6.0.3 on 2026-06-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/Avatar_default.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
